### ISSUE TITLE
question:  is this version of the extension functional?

### ISSUE THREAD

**Issue by SSzretter** [Leonezz/tasks-timeline-view#1]
I am looking to fork the extension and wondering if I should look at this newer version or your other repository?

**Comment by Leonezz** [comment]
Hi @SSzretter this repo is not a functional obsidian plugin like the obsidian-tasks-calendar, this is meant to be a general component for the plugin.

**Comment by BriceChivu** [comment]
Hi Leonezz,
I'm also curious about how to use this newer version.
Could you please guide us through how to incorporate it?

Many thanks in advance

**Comment by Leonezz** [comment]
> Hi Leonezz, I'm also curious about how to use this newer version. Could you please guide us through how to incorporate it?
> 
> Many thanks in advance

The new version is not ready yet so there is no way to incorporate it with obsidian for now.

**Comment by Medullitus** [comment]
Hello. Your sorting option is not working. Can you check that please? @Leonezz
