### ISSUE TITLE
请问这个插件何时能够使用

### ISSUE THREAD

**Issue by lv-ago** [Leonezz/tasks-timeline-view#2]

**Comment by Medullitus** [comment]
???

**Comment by Leonezz** [comment]
最近刚刚毕业入职，工作比较忙，没太多时间开发这个组件。这个组件目前大部分的交互部分都已经完成，但是跟宿主软件数据同步的部分还没搞，所以我也不清楚具体还需要多少时间才能完成。谢谢对插件已经本项目的关注，我会在完成这个组件后第一时间集成到 Obsidian 插件中！
