### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by Medullitus** [Leonezz/tasks-timeline-view#3]
Hello,

Thank you for the plugin. I want to reorder my plugins from newest to oldest. For example, I want my events from 2024 to be at the top and events from 2023 to be at the bottom. However, unfortunately, events from 2023 are appearing at the top, and the sorting option is not working.

**Comment by Medullitus** [comment]
IS anyone here @Leonezz ??

**Comment by Leonezz** [comment]
Hi @Medullitus sorry for the late reply, but this project is not a plugin, it is a component for some plugins I plan to make, so I am not sure how you are using this?
Regarding the issue you raised, as this project is still in prototype and it is not completely developed, I might add new options to make the years also sortable.

**Comment by Leonezz** [comment]
1.

**Comment by Medullitus** [comment]
Hello @Leonezz 

It's nice to hear back from you. I hope everything is going well.

Since I'm new to Github, I'm not sure if notifications are being sent or not. However, you've misunderstood me. I'm not requesting a new feature. I'm saying that the existing sorting features are not working. For instance, I turned off the "Enable Year Header" option in settings. When I make a selection in the "Sort by" section, it doesn't affect the sorting. Is this a bug, or am I missing something? Could you please check on this?

**Comment by Leonezz** [comment]
> Hello @Leonezz
> 
> It's nice to hear back from you. I hope everything is going well.
> 
> Since I'm new to Github, I'm not sure if notifications are being sent or not. However, you've misunderstood me. I'm not requesting a new feature. I'm saying that the existing sorting features are not working. For instance, I turned off the "Enable Year Header" option in settings. When I make a selection in the "Sort by" section, it doesn't affect the sorting. Is this a bug, or am I missing something? Could you please check on this?

Hi @Medullitus, all is well with me, I am just little bit busy and I cannot devote all my time on these projects.
Anyway, are you reporting an issue of the obsidian plugin (https://github.com/Leonezz/obsidian-tasks-calendar-wrapper), if that is the case you should open an issue on that project and I will look it up along with other known issues when I get the time.
